import Head from 'next/head'
import { Row, Col } from 'react-bootstrap'
import ProductList from '../components/ProductList'
import User from '../components/User'

export default function Home() {
  return (
    <>
      <Head>
        <title>AnemalSoul - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-white border-y-blue'>
          <Row>
            <Col md={3} className='border-r-blue'>
              <User />
            </Col>
            <Col md={9}>
              <ProductList />
            </Col>
          </Row>
      </main>
    </>
  )
}
